/**
 * Comprehensive ISO 4217 Currency Data
 *
 * This module provides a complete list of world currencies with their symbols
 * and country mappings. Currencies are sorted alphabetically by name for easy
 * lookup in searchable dropdowns.
 */

export interface CurrencyOption {
  /** ISO 4217 3-letter currency code */
  value: string;
  /** Full currency name */
  label: string;
  /** Currency symbol for display */
  symbol: string;
}

/**
 * Comprehensive list of world currencies (ISO 4217).
 * Sorted alphabetically by label (currency name) for easy searching.
 */
export const CURRENCY_OPTIONS: CurrencyOption[] = [
  { value: "AED", label: "UAE Dirham", symbol: "د.إ" },
  { value: "AFN", label: "Afghan Afghani", symbol: "؋" },
  { value: "ALL", label: "Albanian Lek", symbol: "L" },
  { value: "AMD", label: "Armenian Dram", symbol: "֏" },
  { value: "ANG", label: "Netherlands Antillean Guilder", symbol: "ƒ" },
  { value: "AOA", label: "Angolan Kwanza", symbol: "Kz" },
  { value: "ARS", label: "Argentine Peso", symbol: "AR$" },
  { value: "AUD", label: "Australian Dollar", symbol: "A$" },
  { value: "AWG", label: "Aruban Florin", symbol: "ƒ" },
  { value: "AZN", label: "Azerbaijani Manat", symbol: "₼" },
  { value: "BAM", label: "Bosnia-Herzegovina Convertible Mark", symbol: "KM" },
  { value: "BBD", label: "Barbadian Dollar", symbol: "Bds$" },
  { value: "BDT", label: "Bangladeshi Taka", symbol: "৳" },
  { value: "BGN", label: "Bulgarian Lev", symbol: "лв" },
  { value: "BHD", label: "Bahraini Dinar", symbol: ".د.ب" },
  { value: "BIF", label: "Burundian Franc", symbol: "FBu" },
  { value: "BMD", label: "Bermudan Dollar", symbol: "BD$" },
  { value: "BND", label: "Brunei Dollar", symbol: "B$" },
  { value: "BOB", label: "Bolivian Boliviano", symbol: "Bs." },
  { value: "BRL", label: "Brazilian Real", symbol: "R$" },
  { value: "BSD", label: "Bahamian Dollar", symbol: "B$" },
  { value: "BTN", label: "Bhutanese Ngultrum", symbol: "Nu." },
  { value: "BWP", label: "Botswanan Pula", symbol: "P" },
  { value: "BYN", label: "Belarusian Ruble", symbol: "Br" },
  { value: "BZD", label: "Belize Dollar", symbol: "BZ$" },
  { value: "CAD", label: "Canadian Dollar", symbol: "CA$" },
  { value: "CDF", label: "Congolese Franc", symbol: "FC" },
  { value: "CHF", label: "Swiss Franc", symbol: "CHF" },
  { value: "CLP", label: "Chilean Peso", symbol: "CL$" },
  { value: "CNY", label: "Chinese Yuan", symbol: "¥" },
  { value: "COP", label: "Colombian Peso", symbol: "CO$" },
  { value: "CRC", label: "Costa Rican Colon", symbol: "₡" },
  { value: "CUP", label: "Cuban Peso", symbol: "₱" },
  { value: "CVE", label: "Cape Verdean Escudo", symbol: "Esc" },
  { value: "CZK", label: "Czech Koruna", symbol: "Kč" },
  { value: "DJF", label: "Djiboutian Franc", symbol: "Fdj" },
  { value: "DKK", label: "Danish Krone", symbol: "kr" },
  { value: "DOP", label: "Dominican Peso", symbol: "RD$" },
  { value: "DZD", label: "Algerian Dinar", symbol: "د.ج" },
  { value: "EGP", label: "Egyptian Pound", symbol: "E£" },
  { value: "ERN", label: "Eritrean Nakfa", symbol: "Nfk" },
  { value: "ETB", label: "Ethiopian Birr", symbol: "Br" },
  { value: "EUR", label: "Euro", symbol: "€" },
  { value: "FJD", label: "Fijian Dollar", symbol: "FJ$" },
  { value: "FKP", label: "Falkland Islands Pound", symbol: "FK£" },
  { value: "GBP", label: "British Pound", symbol: "£" },
  { value: "GEL", label: "Georgian Lari", symbol: "₾" },
  { value: "GHS", label: "Ghanaian Cedi", symbol: "GH₵" },
  { value: "GIP", label: "Gibraltar Pound", symbol: "£" },
  { value: "GMD", label: "Gambian Dalasi", symbol: "D" },
  { value: "GNF", label: "Guinean Franc", symbol: "FG" },
  { value: "GTQ", label: "Guatemalan Quetzal", symbol: "Q" },
  { value: "GYD", label: "Guyanaese Dollar", symbol: "GY$" },
  { value: "HKD", label: "Hong Kong Dollar", symbol: "HK$" },
  { value: "HNL", label: "Honduran Lempira", symbol: "L" },
  { value: "HRK", label: "Croatian Kuna", symbol: "kn" },
  { value: "HTG", label: "Haitian Gourde", symbol: "G" },
  { value: "HUF", label: "Hungarian Forint", symbol: "Ft" },
  { value: "IDR", label: "Indonesian Rupiah", symbol: "Rp" },
  { value: "ILS", label: "Israeli Shekel", symbol: "₪" },
  { value: "INR", label: "Indian Rupee", symbol: "₹" },
  { value: "IQD", label: "Iraqi Dinar", symbol: "ع.د" },
  { value: "IRR", label: "Iranian Rial", symbol: "﷼" },
  { value: "ISK", label: "Icelandic Krona", symbol: "kr" },
  { value: "JMD", label: "Jamaican Dollar", symbol: "J$" },
  { value: "JOD", label: "Jordanian Dinar", symbol: "JD" },
  { value: "JPY", label: "Japanese Yen", symbol: "¥" },
  { value: "KES", label: "Kenyan Shilling", symbol: "KSh" },
  { value: "KGS", label: "Kyrgystani Som", symbol: "с" },
  { value: "KHR", label: "Cambodian Riel", symbol: "៛" },
  { value: "KMF", label: "Comorian Franc", symbol: "CF" },
  { value: "KPW", label: "North Korean Won", symbol: "₩" },
  { value: "KRW", label: "South Korean Won", symbol: "₩" },
  { value: "KWD", label: "Kuwaiti Dinar", symbol: "KD" },
  { value: "KYD", label: "Cayman Islands Dollar", symbol: "CI$" },
  { value: "KZT", label: "Kazakhstani Tenge", symbol: "₸" },
  { value: "LAK", label: "Laotian Kip", symbol: "₭" },
  { value: "LBP", label: "Lebanese Pound", symbol: "L£" },
  { value: "LKR", label: "Sri Lankan Rupee", symbol: "Rs" },
  { value: "LRD", label: "Liberian Dollar", symbol: "L$" },
  { value: "LSL", label: "Lesotho Loti", symbol: "L" },
  { value: "LYD", label: "Libyan Dinar", symbol: "LD" },
  { value: "MAD", label: "Moroccan Dirham", symbol: "MAD" },
  { value: "MDL", label: "Moldovan Leu", symbol: "L" },
  { value: "MGA", label: "Malagasy Ariary", symbol: "Ar" },
  { value: "MKD", label: "Macedonian Denar", symbol: "ден" },
  { value: "MMK", label: "Myanmar Kyat", symbol: "K" },
  { value: "MNT", label: "Mongolian Tugrik", symbol: "₮" },
  { value: "MOP", label: "Macanese Pataca", symbol: "MOP$" },
  { value: "MRU", label: "Mauritanian Ouguiya", symbol: "UM" },
  { value: "MUR", label: "Mauritian Rupee", symbol: "Rs" },
  { value: "MVR", label: "Maldivian Rufiyaa", symbol: "Rf" },
  { value: "MWK", label: "Malawian Kwacha", symbol: "MK" },
  { value: "MXN", label: "Mexican Peso", symbol: "MX$" },
  { value: "MYR", label: "Malaysian Ringgit", symbol: "RM" },
  { value: "MZN", label: "Mozambican Metical", symbol: "MT" },
  { value: "NAD", label: "Namibian Dollar", symbol: "N$" },
  { value: "NGN", label: "Nigerian Naira", symbol: "₦" },
  { value: "NIO", label: "Nicaraguan Cordoba", symbol: "C$" },
  { value: "NOK", label: "Norwegian Krone", symbol: "kr" },
  { value: "NPR", label: "Nepalese Rupee", symbol: "Rs" },
  { value: "NZD", label: "New Zealand Dollar", symbol: "NZ$" },
  { value: "OMR", label: "Omani Rial", symbol: "ر.ع." },
  { value: "PAB", label: "Panamanian Balboa", symbol: "B/." },
  { value: "PEN", label: "Peruvian Sol", symbol: "S/" },
  { value: "PGK", label: "Papua New Guinean Kina", symbol: "K" },
  { value: "PHP", label: "Philippine Peso", symbol: "₱" },
  { value: "PKR", label: "Pakistani Rupee", symbol: "Rs" },
  { value: "PLN", label: "Polish Zloty", symbol: "zł" },
  { value: "PYG", label: "Paraguayan Guarani", symbol: "₲" },
  { value: "QAR", label: "Qatari Rial", symbol: "QR" },
  { value: "RON", label: "Romanian Leu", symbol: "lei" },
  { value: "RSD", label: "Serbian Dinar", symbol: "дин" },
  { value: "RUB", label: "Russian Ruble", symbol: "₽" },
  { value: "RWF", label: "Rwandan Franc", symbol: "FRw" },
  { value: "SAR", label: "Saudi Riyal", symbol: "SR" },
  { value: "SBD", label: "Solomon Islands Dollar", symbol: "SI$" },
  { value: "SCR", label: "Seychellois Rupee", symbol: "SR" },
  { value: "SDG", label: "Sudanese Pound", symbol: "SDG" },
  { value: "SEK", label: "Swedish Krona", symbol: "kr" },
  { value: "SGD", label: "Singapore Dollar", symbol: "S$" },
  { value: "SHP", label: "Saint Helena Pound", symbol: "£" },
  { value: "SLL", label: "Sierra Leonean Leone", symbol: "Le" },
  { value: "SOS", label: "Somali Shilling", symbol: "Sh" },
  { value: "SRD", label: "Surinamese Dollar", symbol: "Sr$" },
  { value: "SSP", label: "South Sudanese Pound", symbol: "SS£" },
  { value: "STN", label: "Sao Tome and Principe Dobra", symbol: "Db" },
  { value: "SYP", label: "Syrian Pound", symbol: "S£" },
  { value: "SZL", label: "Swazi Lilangeni", symbol: "E" },
  { value: "THB", label: "Thai Baht", symbol: "฿" },
  { value: "TJS", label: "Tajikistani Somoni", symbol: "SM" },
  { value: "TMT", label: "Turkmenistani Manat", symbol: "T" },
  { value: "TND", label: "Tunisian Dinar", symbol: "DT" },
  { value: "TOP", label: "Tongan Paanga", symbol: "T$" },
  { value: "TRY", label: "Turkish Lira", symbol: "₺" },
  { value: "TTD", label: "Trinidad and Tobago Dollar", symbol: "TT$" },
  { value: "TWD", label: "New Taiwan Dollar", symbol: "NT$" },
  { value: "TZS", label: "Tanzanian Shilling", symbol: "TSh" },
  { value: "UAH", label: "Ukrainian Hryvnia", symbol: "₴" },
  { value: "UGX", label: "Ugandan Shilling", symbol: "USh" },
  { value: "USD", label: "US Dollar", symbol: "$" },
  { value: "UYU", label: "Uruguayan Peso", symbol: "$U" },
  { value: "UZS", label: "Uzbekistan Som", symbol: "so'm" },
  { value: "VES", label: "Venezuelan Bolivar", symbol: "Bs.S" },
  { value: "VND", label: "Vietnamese Dong", symbol: "₫" },
  { value: "VUV", label: "Vanuatu Vatu", symbol: "VT" },
  { value: "WST", label: "Samoan Tala", symbol: "WS$" },
  { value: "XAF", label: "Central African CFA Franc", symbol: "FCFA" },
  { value: "XCD", label: "East Caribbean Dollar", symbol: "EC$" },
  { value: "XOF", label: "West African CFA Franc", symbol: "CFA" },
  { value: "XPF", label: "CFP Franc", symbol: "₣" },
  { value: "YER", label: "Yemeni Rial", symbol: "﷼" },
  { value: "ZAR", label: "South African Rand", symbol: "R" },
  { value: "ZMW", label: "Zambian Kwacha", symbol: "ZK" },
  { value: "ZWL", label: "Zimbabwean Dollar", symbol: "Z$" },
].sort((a, b) => a.label.localeCompare(b.label));

/**
 * Map country names and codes to their default currency.
 * Includes common variations and abbreviations.
 */
export const COUNTRY_TO_CURRENCY: Record<string, string> = {
  // North America
  "United States": "USD",
  "United States of America": "USD",
  USA: "USD",
  US: "USD",
  Canada: "CAD",
  CA: "CAD",
  Mexico: "MXN",
  MX: "MXN",

  // Europe - Eurozone
  Germany: "EUR",
  DE: "EUR",
  France: "EUR",
  FR: "EUR",
  Italy: "EUR",
  IT: "EUR",
  Spain: "EUR",
  ES: "EUR",
  Netherlands: "EUR",
  NL: "EUR",
  Belgium: "EUR",
  BE: "EUR",
  Austria: "EUR",
  AT: "EUR",
  Ireland: "EUR",
  IE: "EUR",
  Portugal: "EUR",
  PT: "EUR",
  Finland: "EUR",
  FI: "EUR",
  Greece: "EUR",
  GR: "EUR",
  Luxembourg: "EUR",
  LU: "EUR",
  Slovakia: "EUR",
  SK: "EUR",
  Slovenia: "EUR",
  SI: "EUR",
  Estonia: "EUR",
  EE: "EUR",
  Latvia: "EUR",
  LV: "EUR",
  Lithuania: "EUR",
  LT: "EUR",
  Malta: "EUR",
  MT: "EUR",
  Cyprus: "EUR",
  CY: "EUR",

  // Europe - Non-Eurozone
  "United Kingdom": "GBP",
  UK: "GBP",
  GB: "GBP",
  Switzerland: "CHF",
  CH: "CHF",
  Sweden: "SEK",
  SE: "SEK",
  Norway: "NOK",
  NO: "NOK",
  Denmark: "DKK",
  DK: "DKK",
  Poland: "PLN",
  PL: "PLN",
  "Czech Republic": "CZK",
  Czechia: "CZK",
  CZ: "CZK",
  Hungary: "HUF",
  HU: "HUF",
  Romania: "RON",
  RO: "RON",
  Bulgaria: "BGN",
  BG: "BGN",
  Croatia: "EUR",
  HR: "EUR",
  Serbia: "RSD",
  RS: "RSD",
  Ukraine: "UAH",
  UA: "UAH",
  Russia: "RUB",
  RU: "RUB",
  Turkey: "TRY",
  TR: "TRY",
  Iceland: "ISK",
  IS: "ISK",
  Albania: "ALL",
  AL: "ALL",
  "North Macedonia": "MKD",
  MK: "MKD",
  Moldova: "MDL",
  MD: "MDL",
  Belarus: "BYN",
  BY: "BYN",
  Georgia: "GEL",
  GE: "GEL",

  // Asia Pacific
  Japan: "JPY",
  JP: "JPY",
  China: "CNY",
  CN: "CNY",
  India: "INR",
  IN: "INR",
  "South Korea": "KRW",
  Korea: "KRW",
  KR: "KRW",
  Singapore: "SGD",
  SG: "SGD",
  "Hong Kong": "HKD",
  HK: "HKD",
  Taiwan: "TWD",
  TW: "TWD",
  Thailand: "THB",
  TH: "THB",
  Indonesia: "IDR",
  ID: "IDR",
  Malaysia: "MYR",
  MY: "MYR",
  Philippines: "PHP",
  PH: "PHP",
  Vietnam: "VND",
  VN: "VND",
  Australia: "AUD",
  AU: "AUD",
  "New Zealand": "NZD",
  NZ: "NZD",
  Pakistan: "PKR",
  PK: "PKR",
  Bangladesh: "BDT",
  BD: "BDT",
  "Sri Lanka": "LKR",
  LK: "LKR",
  Nepal: "NPR",
  NP: "NPR",
  Myanmar: "MMK",
  MM: "MMK",
  Cambodia: "KHR",
  KH: "KHR",
  Laos: "LAK",
  LA: "LAK",
  Mongolia: "MNT",
  MN: "MNT",
  Kazakhstan: "KZT",
  KZ: "KZT",
  Uzbekistan: "UZS",
  UZ: "UZS",
  Kyrgyzstan: "KGS",
  KG: "KGS",
  Tajikistan: "TJS",
  TJ: "TJS",
  Turkmenistan: "TMT",
  TM: "TMT",
  Azerbaijan: "AZN",
  AZ: "AZN",
  Armenia: "AMD",
  AM: "AMD",
  Afghanistan: "AFN",
  AF: "AFN",
  Fiji: "FJD",
  FJ: "FJD",
  "Papua New Guinea": "PGK",
  PG: "PGK",

  // Middle East
  Israel: "ILS",
  IL: "ILS",
  "United Arab Emirates": "AED",
  UAE: "AED",
  AE: "AED",
  "Saudi Arabia": "SAR",
  SA: "SAR",
  Qatar: "QAR",
  QA: "QAR",
  Kuwait: "KWD",
  KW: "KWD",
  Bahrain: "BHD",
  BH: "BHD",
  Oman: "OMR",
  OM: "OMR",
  Jordan: "JOD",
  JO: "JOD",
  Lebanon: "LBP",
  LB: "LBP",
  Iraq: "IQD",
  IQ: "IQD",
  Iran: "IRR",
  IR: "IRR",
  Syria: "SYP",
  SY: "SYP",
  Yemen: "YER",
  YE: "YER",

  // Africa
  "South Africa": "ZAR",
  ZA: "ZAR",
  Nigeria: "NGN",
  NG: "NGN",
  Egypt: "EGP",
  EG: "EGP",
  Morocco: "MAD",
  MA: "MAD",
  Algeria: "DZD",
  DZ: "DZD",
  Tunisia: "TND",
  TN: "TND",
  Libya: "LYD",
  LY: "LYD",
  Kenya: "KES",
  KE: "KES",
  Ethiopia: "ETB",
  ET: "ETB",
  Ghana: "GHS",
  GH: "GHS",
  Tanzania: "TZS",
  TZ: "TZS",
  Uganda: "UGX",
  UG: "UGX",
  Rwanda: "RWF",
  RW: "RWF",
  Zambia: "ZMW",
  ZM: "ZMW",
  Zimbabwe: "ZWL",
  ZW: "ZWL",
  Botswana: "BWP",
  BW: "BWP",
  Namibia: "NAD",
  NA: "NAD",
  Mozambique: "MZN",
  MZ: "MZN",
  Angola: "AOA",
  AO: "AOA",
  Senegal: "XOF",
  SN: "XOF",
  "Ivory Coast": "XOF",
  "Cote d'Ivoire": "XOF",
  CI: "XOF",
  Cameroon: "XAF",
  CM: "XAF",
  Sudan: "SDG",
  SD: "SDG",
  "South Sudan": "SSP",
  SS: "SSP",
  Mauritius: "MUR",
  MU: "MUR",
  Madagascar: "MGA",
  MG: "MGA",
  Malawi: "MWK",
  MW: "MWK",

  // South America
  Brazil: "BRL",
  BR: "BRL",
  Argentina: "ARS",
  AR: "ARS",
  Chile: "CLP",
  CL: "CLP",
  Colombia: "COP",
  CO: "COP",
  Peru: "PEN",
  PE: "PEN",
  Venezuela: "VES",
  VE: "VES",
  Ecuador: "USD", // Uses USD
  EC: "USD",
  Bolivia: "BOB",
  BO: "BOB",
  Paraguay: "PYG",
  PY: "PYG",
  Uruguay: "UYU",
  UY: "UYU",
  Guyana: "GYD",
  GY: "GYD",
  Suriname: "SRD",
  SR: "SRD",

  // Central America & Caribbean
  Panama: "PAB",
  PA: "PAB",
  "Costa Rica": "CRC",
  CR: "CRC",
  Guatemala: "GTQ",
  GT: "GTQ",
  Honduras: "HNL",
  HN: "HNL",
  Nicaragua: "NIO",
  NI: "NIO",
  "El Salvador": "USD", // Uses USD
  SV: "USD",
  Belize: "BZD",
  BZ: "BZD",
  Cuba: "CUP",
  CU: "CUP",
  "Dominican Republic": "DOP",
  DO: "DOP",
  Jamaica: "JMD",
  JM: "JMD",
  Haiti: "HTG",
  HT: "HTG",
  "Trinidad and Tobago": "TTD",
  TT: "TTD",
  Bahamas: "BSD",
  BS: "BSD",
  Barbados: "BBD",
  BB: "BBD",
};

/**
 * Get the default currency for a given country.
 * Falls back to USD if country is not found.
 */
export function getCurrencyForCountry(country: string | null | undefined): string {
  if (!country) return "USD";
  return COUNTRY_TO_CURRENCY[country] ?? "USD";
}

/**
 * Find a currency option by its code.
 */
export function getCurrencyByCode(code: string): CurrencyOption | undefined {
  return CURRENCY_OPTIONS.find((c) => c.value === code);
}

/**
 * Format a currency option for display in dropdown.
 * Example: "$ US Dollar (USD)"
 */
export function formatCurrencyOption(currency: CurrencyOption): string {
  return `${currency.symbol} ${currency.label} (${currency.value})`;
}
