export { HeroSection } from "./HeroSection";
export { MissionsSection } from "./MissionsSection";
export { CenotaphExplainerSection } from "./CenotaphExplainerSection";
export { MethodologySection } from "./MethodologySection";
export { PartnersSection } from "./PartnersSection";
export { CommunitySection } from "./CommunitySection";
export { TestimonialsSliderSection } from "./TestimonialsSliderSection";
export { ScopeSection } from "./ScopeSection";
export { GetInvolvedSection } from "./GetInvolvedSection";
