/**
 * Types for Cenotaph Design Generation
 * Issue: #23 Cenotaph creation wizard
 */

export type DesignStatus = "not_started" | "generating" | "options_ready" | "completed" | "failed";

export interface DesignOption {
  id: string;
  url: string;
  prompt: string;
  createdAt: string;
  conceptId?: string; // Reference to the concept that generated this design
}

/**
 * Creative concept generated by Gemini text model
 * before being rendered into an image
 */
export interface DesignConcept {
  id: string;
  title: string; // Short creative name
  description: string; // Full description for image generation
  styleKeywords: string[]; // Style tags for catalog matching
  createdAt: string;
}

export interface CenotaphDesign {
  options: DesignOption[];
  selectedId: string | null;
  pendingConcepts?: DesignConcept[]; // Concepts waiting to be rendered (4-9)
  selectedConcept?: DesignConcept; // The concept that was selected
}

export interface DesignMetadata {
  attempts: number;
  lastError: string | null;
  modelUsed: string;
  costEstimate: number;
  generatedAt: string;
}

export interface MemorialWithDesign {
  id: string;
  slug: string;
  organizationName: string;
  organizationType: string | null;
  epitaph: string | null;
  userDesignPrompt: string | null;
  designStatus: DesignStatus;
  cenotaphDesign: CenotaphDesign | null;
  cenotaphImageUrl: string | null;
  designMetadata: DesignMetadata | null;
}

export interface OrganizationContext {
  name: string;
  type: string | null;
  industry: string | null;
  foundedDate: string | null;
  closedDate: string | null;
  peakTeamSize: number | null;
  location: string | null;
}

export interface StoryContext {
  epitaph: string | null;
  mainLesson: string | null;
  closureType: string | null;
  keyEvents: string[];
  // AI-generated summary data (from interview process)
  aiSummary?: {
    text: string | null; // Full narrative summary
    keyFacts: string[]; // Extracted key facts
    closurePattern: string | null; // Categorized closure pattern
  } | null;
}

export interface GenerateDesignRequest {
  memorialId: string;
  userPrompt: string;
}

export interface GenerateDesignResponse {
  success: boolean;
  options?: DesignOption[];
  error?: string;
  status?: DesignStatus;
}

export interface SelectDesignRequest {
  memorialId: string;
  selectedDesignId: string;
}

export interface SelectDesignResponse {
  success: boolean;
  imageUrl?: string;
  error?: string;
}

export interface DesignStatusResponse {
  status: DesignStatus;
  options: DesignOption[] | null;
  selectedId: string | null;
  imageUrl: string | null;
  error?: string;
}
