/**
 * Generate TypeScript types from database reference data
 *
 * This script queries the organization_types and lifecycle_stages tables
 * and generates TypeScript union types that match the database values.
 *
 * Run with: npm run generate:types
 *
 * Related Issue: #34
 */

import { createClient } from "@supabase/supabase-js";
import * as fs from "fs";
import * as path from "path";

// Load environment variables from .env.local
function loadEnvFile(): void {
  const envPath = path.join(process.cwd(), ".env.local");
  if (fs.existsSync(envPath)) {
    const content = fs.readFileSync(envPath, "utf-8");
    for (const line of content.split("\n")) {
      const trimmed = line.trim();
      if (trimmed && !trimmed.startsWith("#")) {
        const [key, ...valueParts] = trimmed.split("=");
        if (key && valueParts.length > 0) {
          let value = valueParts.join("=");
          // Remove surrounding quotes if present
          if (
            (value.startsWith('"') && value.endsWith('"')) ||
            (value.startsWith("'") && value.endsWith("'"))
          ) {
            value = value.slice(1, -1);
          }
          process.env[key] = value;
        }
      }
    }
  }
}

loadEnvFile();

const SUPABASE_URL = process.env.NEXT_PUBLIC_SUPABASE_URL;
const SUPABASE_ANON_KEY = process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY;

if (!SUPABASE_URL || !SUPABASE_ANON_KEY) {
  console.error("Error: Missing NEXT_PUBLIC_SUPABASE_URL or NEXT_PUBLIC_SUPABASE_ANON_KEY");
  console.error("Make sure you have a .env.local file with these variables.");
  process.exit(1);
}

const supabase = createClient(SUPABASE_URL, SUPABASE_ANON_KEY);

interface OrgType {
  type_key: string;
}

interface Stage {
  stage_key: string;
}

async function generateTypes(): Promise<void> {
  console.log("Fetching organization types...");

  // Fetch organization types
  const { data: orgTypes, error: orgError } = await supabase
    .from("organization_types")
    .select("type_key")
    .eq("is_active", true)
    .order("display_order");

  if (orgError) {
    console.error("Error fetching organization types:", orgError);
    process.exit(1);
  }

  console.log(`Found ${orgTypes?.length || 0} organization types`);

  // Fetch lifecycle stages
  console.log("Fetching lifecycle stages...");

  const { data: stages, error: stageError } = await supabase
    .from("lifecycle_stages")
    .select("stage_key")
    .eq("is_active", true)
    .order("display_order");

  if (stageError) {
    console.error("Error fetching lifecycle stages:", stageError);
    process.exit(1);
  }

  console.log(`Found ${stages?.length || 0} lifecycle stages`);

  // Generate TypeScript file content
  const orgTypeUnion = (orgTypes as OrgType[]).map((t) => `"${t.type_key}"`).join("\n  | ");

  const stageUnion = (stages as Stage[]).map((s) => `"${s.stage_key}"`).join("\n  | ");

  const content = `/**
 * AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
 *
 * Generated by: scripts/generate-reference-types.ts
 * Source: Supabase database tables (organization_types, lifecycle_stages)
 *
 * To regenerate: npm run generate:types
 */

/**
 * Organization types supported by the platform.
 * Values must match the type_key column in the organization_types table.
 */
export type OrganizationType =
  | ${orgTypeUnion};

/**
 * Organization lifecycle stages.
 * Values must match the stage_key column in the lifecycle_stages table.
 */
export type LifecycleStage =
  | ${stageUnion};
`;

  // Ensure the output directory exists
  const outputDir = path.join(process.cwd(), "src", "types", "generated");
  if (!fs.existsSync(outputDir)) {
    fs.mkdirSync(outputDir, { recursive: true });
    console.log(`Created directory: ${outputDir}`);
  }

  // Write the file
  const outputPath = path.join(outputDir, "reference-types.ts");
  fs.writeFileSync(outputPath, content, "utf-8");

  console.log(`\nGenerated: ${outputPath}`);
  console.log("\nTypes generated successfully!");
  console.log(`  - OrganizationType: ${orgTypes?.length} values`);
  console.log(`  - LifecycleStage: ${stages?.length} values`);
}

generateTypes().catch((err) => {
  console.error("Failed to generate types:", err);
  process.exit(1);
});
